# Generated by Django 6.0.3 on 2026-04-07 10:28

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Charge')], max_length=10, verbose_name='Type')),
                ('is_system', models.BooleanField(default=False, help_text="Les catégories système ne peuvent pas être supprimées via l'API.", verbose_name='Catégorie système')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie comptable',
                'verbose_name_plural': 'Catégories comptables',
                'db_table': 'accounting_categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEcritureComptable',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Charge')], max_length=10, verbose_name='Type')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('auto', 'Automatique')], default='manual', max_length=10, verbose_name='Source')),
                ('ref_type', models.CharField(blank=True, max_length=100, verbose_name='Type référence')),
                ('ref_id', models.UUIDField(blank=True, null=True, verbose_name='ID référence')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='comptabilite.categoriecomptable', verbose_name='Catégorie')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Écriture comptable',
                'verbose_name_plural': 'historical Écritures comptables',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('type', models.CharField(choices=[('income', 'Recette'), ('expense', 'Charge')], max_length=10, verbose_name='Type')),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('source', models.CharField(choices=[('manual', 'Manuel'), ('auto', 'Automatique')], default='manual', max_length=10, verbose_name='Source')),
                ('ref_type', models.CharField(blank=True, max_length=100, verbose_name='Type référence')),
                ('ref_id', models.UUIDField(blank=True, null=True, verbose_name='ID référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecritures', to='comptabilite.categoriecomptable', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'db_table': 'accounting_entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['ref_type', 'ref_id'], name='accounting_ref_idx'), models.Index(fields=['date'], name='accounting_date_idx')],
            },
        ),
    ]
