# Generated by Django 6.0.3 on 2026-04-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_categories_initiales'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriecomptable',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
