# Generated by Django 6.0.3 on 2026-04-20 12:22

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('slogan', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='administration/logo/')),
                ('adresse', models.TextField(blank=True, default='')),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, default='Sénégal', max_length=100)),
                ('ninea', models.CharField(blank=True, default='', max_length=50)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('telephone2', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('site_web', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Paramètres Entreprise',
                'verbose_name_plural': 'Paramètres Entreprise',
            },
        ),
        migrations.CreateModel(
            name='HistoricalParametresEntreprise',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('slogan', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.TextField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, default='')),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, default='Sénégal', max_length=100)),
                ('ninea', models.CharField(blank=True, default='', max_length=50)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('telephone2', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('site_web', models.URLField(blank=True, default='')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Paramètres Entreprise',
                'verbose_name_plural': 'historical Paramètres Entreprise',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
