# Generated by Django 6.0.3 on 2026-04-05 23:54

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial', '0001_initial'),
        ('logistique', '0014_ligne_da_prix_unitaire_estime'),
        ('production', '0011_fournisseur_qualification_contacts_articles_contrats_otd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMouvement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.SlugField(help_text='Identifiant technique immuable (utilisé par les intégrations).', max_length=60, unique=True, verbose_name='Code interne')),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type')),
                ('is_system', models.BooleanField(default=False, help_text='Les catégories système ne peuvent pas être supprimées.', verbose_name='Catégorie système')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie de mouvement',
                'verbose_name_plural': 'Catégories de mouvement',
                'ordering': ['type', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ParametresCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_approbation', models.DecimalField(decimal_places=2, default=Decimal('50000'), help_text='Montant au-delà duquel un mouvement nécessite une approbation manuelle.', max_digits=14, verbose_name='Seuil approbation (FCFA)')),
                ('seuil_alerte_solde_max', models.DecimalField(decimal_places=2, default=Decimal('5000000'), help_text="Alerte si le solde d'une caisse dépasse ce montant.", max_digits=14, verbose_name='Seuil alerte solde max (FCFA)')),
                ('report_automatique_solde', models.BooleanField(default=True, help_text="Si activé, le solde réel de clôture devient automatiquement le solde d'ouverture de la prochaine session.", verbose_name='Report automatique du solde')),
            ],
            options={
                'verbose_name': 'Paramètres caisses',
                'verbose_name_plural': 'Paramètres caisses',
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Solde actuel (FCFA)')),
                ('plafond_alerte', models.DecimalField(blank=True, decimal_places=2, help_text='Alerte si le solde dépasse ce montant.', max_digits=14, null=True, verbose_name='Plafond alerte (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisses_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaisse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Solde actuel (FCFA)')),
                ('plafond_alerte', models.DecimalField(blank=True, decimal_places=2, help_text='Alerte si le solde dépasse ce montant.', max_digits=14, null=True, verbose_name='Plafond alerte (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'historical Caisse',
                'verbose_name_plural': 'historical Caisses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransfertCaisse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('caisse_destination', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisses.caisse', verbose_name='Caisse destination')),
                ('caisse_source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisses.caisse', verbose_name='Caisse source')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transfert de caisse',
                'verbose_name_plural': 'historical Transferts de caisse',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name='Date ouverture')),
                ('date_fermeture', models.DateTimeField(blank=True, null=True, verbose_name='Date fermeture')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Solde ouverture (FCFA)')),
                ('solde_fermeture_reel', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Solde réel clôture (FCFA)')),
                ('ecart', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Écart (FCFA)')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('notes_cloture', models.TextField(blank=True, verbose_name='Notes de clôture')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='caisses.caisse', verbose_name='Caisse')),
                ('ferme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_fermees', to=settings.AUTH_USER_MODEL, verbose_name='Fermé par')),
                ('ouvert_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_ouvertes', to=settings.AUTH_USER_MODEL, verbose_name='Ouvert par')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='TransfertCaisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('caisse_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='caisses.caisse', verbose_name='Caisse destination')),
                ('caisse_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='caisses.caisse', verbose_name='Caisse source')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Transfert de caisse',
                'verbose_name_plural': 'Transferts de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name='Date approbation')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='caisses/justificatifs/', verbose_name='Justificatif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_caisse', to='logistique.boncommande')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='caisses.categoriemouvement', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('facture_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissements_caisse', to='commercial.facturevente')),
                ('ordre_fabrication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_caisse', to='production.ordrefabrication')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='caisses.sessioncaisse', verbose_name='Session')),
                ('transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='caisses.transfertcaisse')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMouvementCaisse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (FCFA)')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name='Date approbation')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('justificatif', models.TextField(blank=True, max_length=100, null=True, verbose_name='Justificatif')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approuve_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('bon_commande', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.boncommande')),
                ('categorie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisses.categoriemouvement', verbose_name='Catégorie')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('facture_vente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commercial.facturevente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ordre_fabrication', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.ordrefabrication')),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisses.sessioncaisse', verbose_name='Session')),
                ('transfert', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caisses.transfertcaisse')),
            ],
            options={
                'verbose_name': 'historical Mouvement de caisse',
                'verbose_name_plural': 'historical Mouvements de caisse',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
