# Generated by Django 6.0.3 on 2026-03-31 23:06

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Catégorie RH',
                'verbose_name_plural': 'Catégories RH',
                'db_table': 'employee_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_taxable', models.BooleanField(default=False, verbose_name='Imposable (incluse dans la base CNSS/AMU)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Type de prime',
                'verbose_name_plural': 'Types de primes',
                'db_table': 'prime_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SocialRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnss_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('4.0'), max_digits=5, verbose_name='Taux CNSS salarié (%)')),
                ('amu_employee_rate', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5, verbose_name='Taux AMU salarié (%)')),
                ('cnss_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('17.5'), max_digits=5, verbose_name='Taux CNSS patronal (%)')),
                ('amu_employer_rate', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5, verbose_name='Taux AMU patronal (%)')),
                ('company_name', models.CharField(default='MANZAY', max_length=200, verbose_name="Nom de l'entreprise")),
                ('company_address', models.CharField(blank=True, max_length=300, null=True, verbose_name="Adresse de l'entreprise")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taux sociaux',
                'verbose_name_plural': 'Taux sociaux',
                'db_table': 'social_rates',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste')),
                ('contract_type', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('temps_partiel', 'Temps partiel'), ('extra', 'Extra'), ('stage', 'Stage')], max_length=20, null=True, verbose_name='Type de contrat')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire mensuel fixe (F CFA)')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('cnss_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° CNSS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('has_social_contributions', models.BooleanField(default=True, verbose_name='Soumis aux cotisations sociales (CNSS/AMU)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='rh.employeecategory', verbose_name='Catégorie RH')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('salaire', 'Salaire'), ('prime', 'Prime'), ('avance', 'Avance'), ('autre', 'Autre')], max_length=20, verbose_name='Type')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant net versé')),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Brut')),
                ('cnss_employee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CNSS salarié')),
                ('amu_employee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AMU salarié')),
                ('cnss_employer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CNSS patronal')),
                ('amu_employer_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='AMU patronal')),
                ('advance_deducted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Avance déduite')),
                ('taxable_primes_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total primes imposables incluses dans la base')),
                ('period_month', models.CharField(blank=True, max_length=7, null=True, verbose_name='Période (YYYY-MM)')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salary_payments', to='rh.employee', verbose_name='Employé')),
                ('linked_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_payments', to='rh.salarypayment', verbose_name='Fiche de salaire liée')),
                ('prime_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rh.primetype', verbose_name='Type de prime')),
            ],
            options={
                'verbose_name': 'Paiement salarial',
                'verbose_name_plural': 'Paiements salariaux',
                'db_table': 'salary_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPrimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant par défaut (F CFA)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prime_settings', to='rh.employeecategory', verbose_name='Catégorie')),
                ('prime_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_settings', to='rh.primetype', verbose_name='Type de prime')),
            ],
            options={
                'verbose_name': 'Paramètre prime catégorie',
                'verbose_name_plural': 'Paramètres primes catégories',
                'db_table': 'category_prime_settings',
                'unique_together': {('category', 'prime_type')},
            },
        ),
    ]
