# Generated by Django 6.0.3 on 2026-04-20 10:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quota_annuel', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Quota annuel par défaut (jours ouvrés)')),
                ('est_paye', models.BooleanField(default=True, verbose_name='Congé payé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Type de congé',
                'verbose_name_plural': 'Types de congé',
                'db_table': 'types_conge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nb_jours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Nombre de jours ouvrés')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('commentaire_rh', models.TextField(blank=True, verbose_name='Commentaire RH (approbation / refus)')),
                ('approuve_le', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé / refusé par')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='rh.employee', verbose_name='Employé')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='rh.typeconge', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'db_table': 'demandes_conge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('demi_journee', 'Demi-journée'), ('conge', 'Congé')], default='present', max_length=20, verbose_name='Statut')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='rh.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'db_table': 'pointages',
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('jours_acquis', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Jours acquis')),
                ('jours_pris', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Jours pris')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='rh.employee', verbose_name='Employé')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soldes', to='rh.typeconge', verbose_name='Type de congé')),
            ],
            options={
                'verbose_name': 'Solde de congé',
                'verbose_name_plural': 'Soldes de congé',
                'db_table': 'soldes_conge',
                'ordering': ['employee__name', 'type_conge__name'],
                'unique_together': {('employee', 'type_conge', 'annee')},
            },
        ),
    ]
