# Generated by Django 6.0.3 on 2026-04-30 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_typeconge_demandeconge_pointage_soldeconge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(max_length=7, unique=True, verbose_name='Période (YYYY-MM)')),
                ('payment_date', models.DateField(verbose_name='Date de paiement prévue')),
                ('data', models.JSONField(default=dict, verbose_name='Données de la grille')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis')], default='draft', max_length=20, verbose_name='Statut')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créé le')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dernière modification par')),
            ],
            options={
                'verbose_name': 'Brouillon de paie',
                'verbose_name_plural': 'Brouillons de paie',
                'db_table': 'payroll_drafts',
                'ordering': ['-period_month'],
            },
        ),
    ]
