# Generated by Django 6.0.3 on 2026-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_typeconge_mode_acquisition_soldeconge_restructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('is_recurrent', models.BooleanField(default=False, verbose_name='Récurrent (même mois/jour chaque année)')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'jours_feries',
                'ordering': ['date'],
            },
        ),
    ]
