# Generated by Django 6.0.3 on 2026-03-19 21:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockarticle',
            name='qte_reappro',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Quantité standard à commander pour le réappro', max_digits=14, verbose_name='Quantité de réapprovisionnement'),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='stock_min',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Niveau en dessous duquel réapprovisionner immédiatement', max_digits=14, verbose_name='Stock minimum'),
        ),
        migrations.AddField(
            model_name='stockarticle',
            name='stock_securite',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Tampon pour absorber les aléas de livraison', max_digits=14, verbose_name='Stock de sécurité'),
        ),
        migrations.CreateModel(
            name='EvaluationFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_qualite', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note qualité (1-5)')),
                ('note_delai', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note délai (1-5)')),
                ('note_prix', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Note prix (1-5)')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='logistique.boncommande')),
                ('evaluateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='logistique.fournisseur')),
            ],
            options={
                'verbose_name': 'Évaluation fournisseur',
                'verbose_name_plural': 'Évaluations fournisseurs',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence interne')),
                ('ref_fournisseur', models.CharField(blank=True, max_length=50, verbose_name='Réf. facture fournisseur')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée intégralement'), ('annulee', 'Annulée')], default='en_attente', max_length=25, verbose_name='Statut')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT (FCFA)')),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA (FCFA)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TTC (FCFA)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé (FCFA)')),
                ('date_facture', models.DateField(verbose_name='Date de la facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='logistique.boncommande')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='logistique.fournisseur')),
                ('reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='logistique.reception')),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseurs',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='InventaireSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé'), ('annule', 'Annulé')], default='en_cours', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_debut', models.DateTimeField(auto_now_add=True, verbose_name='Date début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date fin')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Session d'inventaire",
                'verbose_name_plural': "Sessions d'inventaire",
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (FCFA)')),
                ('date_paiement', models.DateField(verbose_name='Date du paiement')),
                ('mode_paiement', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money')], max_length=15, verbose_name='Mode')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='logistique.facturefournisseur')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_theorique', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité système')),
                ('quantite_comptee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité comptée')),
                ('justification', models.TextField(blank=True, verbose_name='Justification écart')),
                ('valide', models.BooleanField(default=False, verbose_name='Ligne validée')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.lot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='logistique.inventairesession')),
            ],
            options={
                'verbose_name': 'Ligne inventaire',
                'verbose_name_plural': 'Lignes inventaire',
                'unique_together': {('session', 'lot')},
            },
        ),
    ]
