# Generated by Django 6.0.3 on 2026-03-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0002_stockarticle_qte_reappro_stockarticle_stock_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='montant_estime',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant estimé de la commande — au-delà de 5 000 000 FCFA, approbation direction requise', max_digits=14, null=True, verbose_name='Montant estimé (FCFA)'),
        ),
        migrations.AddField(
            model_name='historicaldemandeachat',
            name='montant_estime',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant estimé de la commande — au-delà de 5 000 000 FCFA, approbation direction requise', max_digits=14, null=True, verbose_name='Montant estimé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='demandeachat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('traitee', 'Traitée (BC émis)'), ('attente_direction', 'En attente approbation direction')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicaldemandeachat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('traitee', 'Traitée (BC émis)'), ('attente_direction', 'En attente approbation direction')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
    ]
