# Generated by Django 6.0.3 on 2026-03-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0003_demandeachat_montant_estime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereception',
            name='conforme',
            field=models.BooleanField(default=True, verbose_name='Conforme'),
        ),
        migrations.AddField(
            model_name='lignereception',
            name='motif_non_conformite',
            field=models.TextField(blank=True, verbose_name='Motif non-conformité'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('confirme', 'Confirmé par le fournisseur'), ('partiel', 'Partiellement reçu'), ('recu', 'Reçu intégralement'), ('annule', 'Annulé')], default='brouillon', max_length=15, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='historicalboncommande',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('confirme', 'Confirmé par le fournisseur'), ('partiel', 'Partiellement reçu'), ('recu', 'Reçu intégralement'), ('annule', 'Annulé')], default='brouillon', max_length=15, verbose_name='Statut'),
        ),
    ]
