# Generated by Django 6.0.3 on 2026-03-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0004_bc_confirme_reception_qualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='piece_jointe',
            field=models.FileField(blank=True, help_text='Bon, facture ou tout justificatif du mouvement', null=True, upload_to='mouvements/', verbose_name='Pièce jointe'),
        ),
    ]
