# Generated by Django 6.0.3 on 2026-03-21 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0005_piece_jointe_mouvement'),
        ('production', '0004_article_gere_par_lot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ligneinventaire',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_inventaire', to='production.article', verbose_name='Article (stock global)'),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.lot', verbose_name='Lot'),
        ),
        migrations.AddConstraint(
            model_name='ligneinventaire',
            constraint=models.UniqueConstraint(condition=models.Q(('lot__isnull', False)), fields=('session', 'lot'), name='unique_ligne_inv_session_lot'),
        ),
        migrations.AddConstraint(
            model_name='ligneinventaire',
            constraint=models.UniqueConstraint(condition=models.Q(('article__isnull', False), ('lot__isnull', True)), fields=('session', 'article'), name='unique_ligne_inv_session_article'),
        ),
    ]
