# Generated by Django 6.0.3 on 2026-03-22 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0006_ligne_inventaire_sans_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneboncommande',
            name='ligne_da',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bc', to='logistique.lignedemandeachat', verbose_name="Ligne DA d'origine"),
        ),
        migrations.AddField(
            model_name='lignedemandeachat',
            name='quantite_commandee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Quantité déjà commandée (BCs)'),
        ),
    ]
