# Generated by Django 6.0.3 on 2026-03-23 10:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0007_ligneboncommande_ligne_da_and_more'),
        ('production', '0011_fournisseur_qualification_contacts_articles_contrats_otd'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='qualification',
            field=models.CharField(choices=[('en_evaluation', 'En évaluation'), ('approuve', 'Approuvé'), ('suspendu', 'Suspendu'), ('blackliste', 'Blacklisté')], default='en_evaluation', max_length=20, verbose_name='Qualification'),
        ),
        migrations.AddField(
            model_name='historicalfournisseur',
            name='qualification',
            field=models.CharField(choices=[('en_evaluation', 'En évaluation'), ('approuve', 'Approuvé'), ('suspendu', 'Suspendu'), ('blackliste', 'Blacklisté')], default='en_evaluation', max_length=20, verbose_name='Qualification'),
        ),
        migrations.CreateModel(
            name='ContactFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Rôle / fonction')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('principal', models.BooleanField(default=False, help_text='Un seul contact principal par fournisseur.', verbose_name='Contact principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='logistique.fournisseur')),
            ],
            options={
                'verbose_name': 'Contact fournisseur',
                'verbose_name_plural': 'Contacts fournisseur',
                'ordering': ['-principal', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ContratFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence contrat')),
                ('type_contrat', models.CharField(choices=[('cadre', 'Contrat-cadre'), ('exclusivite', 'Exclusivité'), ('annuel', 'Accord annuel'), ('ponctuel', 'Achat ponctuel')], default='cadre', max_length=20, verbose_name='Type')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond du contrat ; laisser vide si illimité.', max_digits=14, null=True, verbose_name='Montant maximum (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, verbose_name='Description / conditions')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='logistique.fournisseur')),
            ],
            options={
                'verbose_name': 'Contrat fournisseur',
                'verbose_name_plural': 'Contrats fournisseurs',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FournisseurArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_fournisseur', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (FCFA)')),
                ('delai_livraison', models.PositiveSmallIntegerField(default=7, verbose_name='Délai livraison (jours)')),
                ('quantite_min_commande', models.DecimalField(decimal_places=3, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité minimum de commande')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_derniere_commande', models.DateField(blank=True, null=True, verbose_name='Dernière commande')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='production.article')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_fournis', to='logistique.fournisseur')),
            ],
            options={
                'verbose_name': 'Article fournisseur',
                'verbose_name_plural': 'Articles fournisseurs',
                'ordering': ['article__designation'],
                'unique_together': {('fournisseur', 'article')},
            },
        ),
    ]
