# Generated by Django 6.0.3 on 2026-03-23 11:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0008_fournisseur_qualification_contacts_articles_contrats_otd'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFraisAnnexe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du frais')),
                ('type_calcul', models.CharField(choices=[('montant_fixe', 'Montant fixe (FCFA)'), ('pourcentage', 'Pourcentage du HT (%)')], default='pourcentage', max_length=15, verbose_name='Type de calcul')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type de frais annexe',
                'verbose_name_plural': 'Types de frais annexes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='boncommande',
            name='adresse_livraison',
            field=models.TextField(blank=True, help_text="Laisser vide pour utiliser l'adresse par défaut de l'entreprise.", verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='montant_frais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Frais annexes (FCFA)'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Version (amendements)'),
        ),
        migrations.AddField(
            model_name='historicalboncommande',
            name='adresse_livraison',
            field=models.TextField(blank=True, help_text="Laisser vide pour utiliser l'adresse par défaut de l'entreprise.", verbose_name='Adresse de livraison'),
        ),
        migrations.AddField(
            model_name='historicalboncommande',
            name='montant_frais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Frais annexes (FCFA)'),
        ),
        migrations.AddField(
            model_name='historicalboncommande',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Version (amendements)'),
        ),
        migrations.AddField(
            model_name='ligneboncommande',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18, help_text='Taux de TVA applicable à cette ligne (ex. 18 pour 18 %).', max_digits=5, verbose_name='Taux TVA (%)'),
        ),
        migrations.CreateModel(
            name='FraisAnnexeBC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valeur', models.DecimalField(decimal_places=4, help_text='Montant en FCFA ou pourcentage selon le type de calcul.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur')),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frais_annexes', to='logistique.boncommande')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='logistique.typefraisannexe')),
            ],
            options={
                'verbose_name': 'Frais annexe BC',
                'verbose_name_plural': 'Frais annexes BC',
                'ordering': ['type_frais__nom'],
                'unique_together': {('bon_commande', 'type_frais')},
            },
        ),
    ]
