# Generated by Django 6.0.3 on 2026-03-23 14:02

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0009_bc_adresse_version_frais_annexes_taux_tva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='numero_bl_fournisseur',
            field=models.CharField(blank=True, help_text='Numéro du bon de livraison fournisseur.', max_length=50, verbose_name='N° BL fournisseur'),
        ),
        migrations.AddField(
            model_name='reception',
            name='piece_jointe_bl',
            field=models.FileField(blank=True, help_text='Scan ou photo du bon de livraison fournisseur.', null=True, upload_to='receptions/bl/', verbose_name='BL fournisseur (scan)'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type',
            field=models.CharField(choices=[('entree_recep', 'Entrée — Réception fournisseur'), ('entree_prod', 'Entrée — Production (PF)'), ('sortie_prod', 'Sortie — Consommation production'), ('sortie_vente', 'Sortie — Vente client'), ('ajust_pos', 'Ajustement positif (inventaire)'), ('ajust_neg', 'Ajustement négatif (inventaire)'), ('transfert', 'Transfert inter-entrepôt'), ('retour_fourn', 'Retour — Fournisseur')], max_length=20, verbose_name='Type de mouvement'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejetee', 'Rejetée (retour fournisseur)')], default='en_cours', max_length=10, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='HistoricalReception',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('reference', models.CharField(db_index=True, max_length=20, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('validee', 'Validée'), ('rejetee', 'Rejetée (retour fournisseur)')], default='en_cours', max_length=10, verbose_name='Statut')),
                ('date_reception', models.DateField(verbose_name='Date de réception')),
                ('numero_bl_fournisseur', models.CharField(blank=True, help_text='Numéro du bon de livraison fournisseur.', max_length=50, verbose_name='N° BL fournisseur')),
                ('piece_jointe_bl', models.TextField(blank=True, help_text='Scan ou photo du bon de livraison fournisseur.', max_length=100, null=True, verbose_name='BL fournisseur (scan)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bon_commande', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.boncommande')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recue_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Réception',
                'verbose_name_plural': 'historical Réceptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRetourFournisseur',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('reference', models.CharField(db_index=True, max_length=20, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé')], default='en_cours', max_length=10, verbose_name='Statut')),
                ('date_retour', models.DateField(verbose_name='Date de retour')),
                ('motif', models.TextField(verbose_name='Motif du retour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modif', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, db_constraint=False, help_text='Dénormalisé depuis la réception pour faciliter les requêtes.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.fournisseur')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reception', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.reception', verbose_name="Réception d'origine")),
            ],
            options={
                'verbose_name': 'historical Retour fournisseur',
                'verbose_name_plural': 'historical Retours fournisseur',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RetourFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('valide', 'Validé')], default='en_cours', max_length=10, verbose_name='Statut')),
                ('date_retour', models.DateField(verbose_name='Date de retour')),
                ('motif', models.TextField(verbose_name='Motif du retour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(help_text='Dénormalisé depuis la réception pour faciliter les requêtes.', on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='logistique.fournisseur')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='logistique.reception', verbose_name="Réception d'origine")),
            ],
            options={
                'verbose_name': 'Retour fournisseur',
                'verbose_name_plural': 'Retours fournisseur',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneRetour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite_retournee', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité retournée')),
                ('ligne_reception', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='logistique.lignereception')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='logistique.retourfournisseur')),
            ],
            options={
                'verbose_name': 'Ligne retour',
                'verbose_name_plural': 'Lignes retour',
            },
        ),
    ]
