# Generated by Django 6.0.3 on 2026-03-26 08:26

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0010_reception_retour_bl_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturefournisseur',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_approuvees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='date_approbation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation"),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='facture_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs', to='logistique.facturefournisseur', verbose_name="Facture d'origine (avoirs uniquement)"),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='piece_jointe',
            field=models.FileField(blank=True, help_text='Scan ou photo de la facture papier reçue.', null=True, upload_to='factures/', verbose_name='Scan facture'),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='type_document',
            field=models.CharField(choices=[('facture', 'Facture'), ('avoir', 'Avoir / Note de crédit'), ('frais', 'Facture de frais (hors BC)')], default='facture', max_length=10, verbose_name='Type de document'),
        ),
        migrations.AddField(
            model_name='paiementfacture',
            name='annule',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
        migrations.AddField(
            model_name='paiementfacture',
            name='piece_jointe',
            field=models.FileField(blank=True, help_text='Reçu virement, copie chèque, confirmation Mobile Money…', null=True, upload_to='paiements/', verbose_name='Justificatif paiement'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant HT (FCFA)'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TTC (FCFA)'),
        ),
        migrations.AlterField(
            model_name='facturefournisseur',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise pour approbation'), ('attente_direction', 'En attente approbation direction'), ('en_attente', 'Approuvée — En attente de paiement'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée intégralement'), ('annulee', 'Annulée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=25, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='paiementfacture',
            name='mode_paiement',
            field=models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('avoir', 'Imputation avoir fournisseur')], max_length=15, verbose_name='Mode'),
        ),
        migrations.CreateModel(
            name='EcheanceFacture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (FCFA)')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('payee', models.BooleanField(default=False, verbose_name='Payée')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='logistique.facturefournisseur')),
            ],
            options={
                'verbose_name': 'Échéance facture',
                'verbose_name_plural': 'Échéances facture',
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFactureFournisseur',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('reference', models.CharField(db_index=True, max_length=20, verbose_name='Référence interne')),
                ('ref_fournisseur', models.CharField(blank=True, max_length=50, verbose_name='Réf. facture fournisseur')),
                ('type_document', models.CharField(choices=[('facture', 'Facture'), ('avoir', 'Avoir / Note de crédit'), ('frais', 'Facture de frais (hors BC)')], default='facture', max_length=10, verbose_name='Type de document')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumise', 'Soumise pour approbation'), ('attente_direction', 'En attente approbation direction'), ('en_attente', 'Approuvée — En attente de paiement'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée intégralement'), ('annulee', 'Annulée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=25, verbose_name='Statut')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant HT (FCFA)')),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='TVA (FCFA)')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant TTC (FCFA)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant payé (FCFA)')),
                ('date_facture', models.DateField(verbose_name='Date de la facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('piece_jointe', models.TextField(blank=True, help_text='Scan ou photo de la facture papier reçue.', max_length=100, null=True, verbose_name='Scan facture')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modif', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approuve_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bon_commande', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.boncommande')),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facture_origine', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.facturefournisseur', verbose_name="Facture d'origine (avoirs uniquement)")),
                ('fournisseur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.fournisseur')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reception', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.reception')),
            ],
            options={
                'verbose_name': 'historical Facture fournisseur',
                'verbose_name_plural': 'historical Factures fournisseurs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LigneFactureFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire (FCFA)')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18, max_digits=5, verbose_name='Taux TVA (%)')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='logistique.facturefournisseur')),
                ('ligne_bc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='logistique.ligneboncommande', verbose_name="Ligne BC d'origine")),
            ],
            options={
                'verbose_name': 'Ligne facture fournisseur',
                'verbose_name_plural': 'Lignes facture fournisseur',
            },
        ),
    ]
