# Generated by Django 6.0.3 on 2026-03-26 10:07

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0011_facture_workflow_lignes_echeances'),
        ('production', '0011_fournisseur_qualification_contacts_articles_contrats_otd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventairesession',
            name='articles_cibles',
            field=models.ManyToManyField(blank=True, help_text='Actif si type_perimetre=articles', related_name='sessions_inventaire', to='production.article', verbose_name='Articles ciblés'),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='aveugle',
            field=models.BooleanField(default=False, help_text='Si activé, la quantité théorique est masquée aux opérateurs lors de la saisie.', verbose_name='Comptage en aveugle'),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Liste de types ex: ["mp","pf"] — actif si type_perimetre=categorie', verbose_name="Types d'articles ciblés"),
        ),
        migrations.AddField(
            model_name='inventairesession',
            name='type_perimetre',
            field=models.CharField(choices=[('complet', 'Inventaire complet'), ('categorie', "Par type d'article"), ('articles', 'Articles spécifiques')], default='complet', max_length=15, verbose_name='Type de périmètre'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='prix_unitaire_valorisation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire valorisation (FCFA)'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='quantite_systeme_validation',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité système à la validation'),
        ),
        migrations.AddField(
            model_name='ligneinventaire',
            name='statut_saisie',
            field=models.CharField(choices=[('non_saisie', 'Non saisie'), ('saisie', 'Saisie'), ('validee', 'Validée')], default='non_saisie', max_length=15, verbose_name='Statut saisie'),
        ),
        migrations.AlterField(
            model_name='ligneinventaire',
            name='quantite_theorique',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité système (gel)'),
        ),
        migrations.CreateModel(
            name='HistoricalLigneInventaire',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('quantite_theorique', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantité système (gel)')),
                ('quantite_systeme_validation', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité système à la validation')),
                ('quantite_comptee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Quantité comptée')),
                ('prix_unitaire_valorisation', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prix unitaire valorisation (FCFA)')),
                ('justification', models.TextField(blank=True, verbose_name='Justification écart')),
                ('statut_saisie', models.CharField(choices=[('non_saisie', 'Non saisie'), ('saisie', 'Saisie'), ('validee', 'Validée')], default='non_saisie', max_length=15, verbose_name='Statut saisie')),
                ('valide', models.BooleanField(default=False, verbose_name='Ligne validée')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.article', verbose_name='Article (stock global)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.lot', verbose_name='Lot')),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.inventairesession')),
            ],
            options={
                'verbose_name': 'historical Ligne inventaire',
                'verbose_name_plural': 'historical Lignes inventaire',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStockArticle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('quantite_disponible', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantité disponible')),
                ('quantite_reservee', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Quantité réservée (OFs confirmés)')),
                ('seuil_alerte', models.DecimalField(decimal_places=3, default=0, help_text='Déclenche une alerte si quantité dispo < seuil', max_digits=14, verbose_name="Seuil d'alerte")),
                ('stock_min', models.DecimalField(decimal_places=3, default=0, help_text='Niveau en dessous duquel réapprovisionner immédiatement', max_digits=14, verbose_name='Stock minimum')),
                ('stock_securite', models.DecimalField(decimal_places=3, default=0, help_text='Tampon pour absorber les aléas de livraison', max_digits=14, verbose_name='Stock de sécurité')),
                ('qte_reappro', models.DecimalField(decimal_places=3, default=0, help_text='Quantité standard à commander pour le réappro', max_digits=14, verbose_name='Quantité de réapprovisionnement')),
                ('derniere_maj', models.DateTimeField(blank=True, editable=False, verbose_name='Dernière mise à jour')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('article', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.article', verbose_name='Article')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Stock article',
                'verbose_name_plural': 'historical Stocks articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
