# Generated by Django 6.0.3 on 2026-03-26 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0012_inventaire_gel_perimetre_historique'),
        ('production', '0011_fournisseur_qualification_contacts_articles_contrats_otd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='date_comptable',
            field=models.DateField(blank=True, help_text='Date économique réelle du mouvement (ex : réception livrée vendredi, saisie lundi). Si vide, date_mouvement est utilisée pour les rapports.', null=True, verbose_name='Date comptable'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['article', 'date_comptable'], name='logistique__article_90272e_idx'),
        ),
    ]
