# Generated by Django 6.0.3 on 2026-04-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0013_mouvements_date_comptable_filtres'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedemandeachat',
            name='prix_unitaire_estime',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix estimé pour calculer le montant total de la DA', max_digits=14, null=True, verbose_name='Prix unitaire estimé (FCFA)'),
        ),
    ]
