# Generated by Django 6.0.3 on 2026-04-18 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0015_conditions_tarifaires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalboncommande',
            name='montant_frais',
        ),
        migrations.RemoveField(
            model_name='historicalboncommande',
            name='tva',
        ),
        migrations.AlterField(
            model_name='conditionappliqueebc',
            name='valeur',
            field=models.DecimalField(decimal_places=4, help_text="Valeur capturée au moment de l'application (snapshot).", max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur'),
        ),
    ]
