# Generated by Django 6.0.3 on 2026-04-20 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0016_remove_historicalboncommande_montant_frais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeachat',
            name='da_parente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='logistique.demandeachat', verbose_name='DA parente (V1)'),
        ),
        migrations.AddField(
            model_name='demandeachat',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='historicaldemandeachat',
            name='da_parente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistique.demandeachat', verbose_name='DA parente (V1)'),
        ),
        migrations.AddField(
            model_name='historicaldemandeachat',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Version'),
        ),
    ]
