# Generated by Django 6.0.3 on 2026-03-19 16:46

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code article')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('type', models.CharField(choices=[('mp', 'Matière première'), ('pf', 'Produit fini'), ('sf', 'Semi-fini'), ('co', 'Consommable')], max_length=5, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=50, verbose_name='Libellé')),
                ('type', models.CharField(choices=[('masse', 'Masse'), ('volume', 'Volume'), ('longueur', 'Longueur'), ('surface', 'Surface'), ('unite', 'Unité')], default='unite', max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalNomenclature',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('quantite_base', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité produite (base)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modif', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'type__in': ['pf', 'sf']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.article', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'historical Nomenclature',
                'verbose_name_plural': 'historical Nomenclatures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('quantite_base', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité produite (base)')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures_creees', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(limit_choices_to={'type__in': ['pf', 'sf']}, on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='production.article', verbose_name='Produit fini')),
            ],
            options={
                'verbose_name': 'Nomenclature',
                'verbose_name_plural': 'Nomenclatures',
                'ordering': ['produit_fini__designation', '-version'],
                'unique_together': {('produit_fini', 'version')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrdreFabrication',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('reference', models.CharField(db_index=True, max_length=20, verbose_name='Référence')),
                ('quantite_prevue', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité prévue')),
                ('quantite_produite', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité produite')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date début réelle')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date fin réelle')),
                ('ligne_prod', models.CharField(blank=True, max_length=50, verbose_name='Ligne de production')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('date_modif', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cree_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nomenclature', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.nomenclature', verbose_name='Nomenclature')),
            ],
            options={
                'verbose_name': 'historical Ordre de fabrication',
                'verbose_name_plural': 'historical Ordres de fabrication',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('quantite_prevue', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité prévue')),
                ('quantite_produite', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité produite')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('cloture', 'Clôturé'), ('annule', 'Annulé')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date début réelle')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date fin réelle')),
                ('ligne_prod', models.CharField(blank=True, max_length=50, verbose_name='Ligne de production')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ofs_crees', to=settings.AUTH_USER_MODEL)),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres', to='production.nomenclature', verbose_name='Nomenclature')),
            ],
            options={
                'verbose_name': 'Ordre de fabrication',
                'verbose_name_plural': 'Ordres de fabrication',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lot', models.CharField(max_length=50, unique=True, verbose_name='N° de lot')),
                ('date_fabrication', models.DateField(verbose_name='Date de fabrication')),
                ('date_peremption', models.DateField(blank=True, null=True, verbose_name='Date de péremption')),
                ('quantite_initiale', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité initiale')),
                ('quantite_restante', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité restante')),
                ('cout_unitaire', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Coût unitaire (FCFA)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('epuise', 'Épuisé'), ('bloque', 'Bloqué (qualité)'), ('perime', 'Périmé')], default='disponible', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='production.article')),
                ('ordre_fabrication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_produits', to='production.ordrefabrication')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['article', 'date_peremption'],
            },
        ),
        migrations.CreateModel(
            name='CoutRevient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cout_matieres', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût matières (FCFA)')),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Coût main d'œuvre (FCFA)")),
                ('cout_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Charges indirectes (FCFA)')),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût total (FCFA)')),
                ('cout_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût unitaire (FCFA)')),
                ('cout_standard', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Coût standard (FCFA)')),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('of', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cout_revient', to='production.ordrefabrication')),
            ],
            options={
                'verbose_name': 'Coût de revient',
            },
        ),
        migrations.CreateModel(
            name='ConsommationLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Quantité consommée')),
                ('date_consommation', models.DateTimeField(auto_now_add=True)),
                ('lot_mp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consommations_comme_mp', to='production.lot', verbose_name='Lot matière première')),
                ('lot_pf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composants_mp', to='production.lot', verbose_name='Lot produit fini')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='production.ordrefabrication')),
            ],
            options={
                'verbose_name': 'Consommation de lot',
                'verbose_name_plural': 'Consommations de lots',
            },
        ),
        migrations.CreateModel(
            name='AffectationEmployeOF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_prod', models.CharField(blank=True, max_length=100, verbose_name='Rôle sur OF')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_of', to=settings.AUTH_USER_MODEL)),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='production.ordrefabrication')),
            ],
        ),
        migrations.CreateModel(
            name='Perte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('rebut', 'Rebut'), ('dechet', 'Déchet'), ('perte', 'Perte process'), ('casse', 'Casse')], max_length=10, verbose_name='Type')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Quantité')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.article')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertes', to='production.ordrefabrication')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perte / Rebut',
                'verbose_name_plural': 'Pertes & Rebuts',
            },
        ),
        migrations.CreateModel(
            name='HistoricalArticle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='Code article')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('type', models.CharField(choices=[('mp', 'Matière première'), ('pf', 'Produit fini'), ('sf', 'Semi-fini'), ('co', 'Consommable')], max_length=5, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unite', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.unitemesure', verbose_name='Unité de mesure')),
            ],
            options={
                'verbose_name': 'historical Article',
                'verbose_name_plural': 'historical Articles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='article',
            name='unite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='production.unitemesure', verbose_name='Unité de mesure'),
        ),
        migrations.CreateModel(
            name='LigneNomenclature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Quantité')),
                ('taux_perte', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage de perte standard pour cette composante', max_digits=5, verbose_name='Taux de perte (%)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('matiere', models.ForeignKey(limit_choices_to={'type__in': ['mp', 'co', 'sf']}, on_delete=django.db.models.deletion.PROTECT, related_name='utilisations_bom', to='production.article', verbose_name='Matière première')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='production.nomenclature')),
            ],
            options={
                'verbose_name': 'Ligne de nomenclature',
                'verbose_name_plural': 'Lignes de nomenclature',
                'unique_together': {('nomenclature', 'matiere')},
            },
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(condition=models.Q(('statut', 'disponible')), fields=['article', 'date_peremption'], name='idx_lot_fifo'),
        ),
        migrations.AlterUniqueTogether(
            name='affectationemployeof',
            unique_together={('of', 'employe')},
        ),
    ]
