# Generated by Django 6.0.3 on 2026-03-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordrefabrication',
            name='seuil_rendement',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Alerte si rendement réel < seuil (en %)', max_digits=5, verbose_name='Seuil rendement alerte (%)'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='seuil_rendement',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Alerte si rendement réel < seuil (en %)', max_digits=5, verbose_name='Seuil rendement alerte (%)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('mp', 'Matière première'), ('pf', 'Produit fini'), ('sf', 'Semi-fini'), ('emballage', 'Emballage/Consommable')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='type',
            field=models.CharField(choices=[('mp', 'Matière première'), ('pf', 'Produit fini'), ('sf', 'Semi-fini'), ('emballage', 'Emballage/Consommable')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='lignenomenclature',
            name='matiere',
            field=models.ForeignKey(limit_choices_to={'type__in': ['mp', 'emballage', 'sf']}, on_delete=django.db.models.deletion.PROTECT, related_name='utilisations_bom', to='production.article', verbose_name='Matière première'),
        ),
    ]
