# Generated by Django 6.0.3 on 2026-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_historicalordrefabrication_seuil_rendement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnomenclature',
            name='cout_standard',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût de revient standard par unité — référence pour comparer avec le coût réel', max_digits=14, verbose_name='Coût standard (FCFA/unité produite)'),
        ),
        migrations.AddField(
            model_name='historicalordrefabrication',
            name='seuil_perte',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Alerte si les pertes cumulées dépassent ce % de la quantité prévue', max_digits=5, verbose_name='Seuil perte alerte (%)'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='cout_standard',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût de revient standard par unité — référence pour comparer avec le coût réel', max_digits=14, verbose_name='Coût standard (FCFA/unité produite)'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='seuil_perte',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Alerte si les pertes cumulées dépassent ce % de la quantité prévue', max_digits=5, verbose_name='Seuil perte alerte (%)'),
        ),
    ]
