# Generated by Django 6.0.3 on 2026-03-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_seuil_perte_cout_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gere_par_lot',
            field=models.BooleanField(default=True, help_text='Si activé, le stock est suivi lot par lot (numéro, FIFO, péremption). Sinon, le stock est suivi en quantité globale sans notion de lot.', verbose_name='Géré par lot'),
        ),
        migrations.AddField(
            model_name='historicalarticle',
            name='gere_par_lot',
            field=models.BooleanField(default=True, help_text='Si activé, le stock est suivi lot par lot (numéro, FIFO, péremption). Sinon, le stock est suivi en quantité globale sans notion de lot.', verbose_name='Géré par lot'),
        ),
    ]
