# Generated by Django 6.0.3 on 2026-03-22 22:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_article_catalogue_extensions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservationlot',
            name='unique_reservation_of_lot',
        ),
        migrations.AlterField(
            model_name='article',
            name='code_barre',
            field=models.CharField(blank=True, help_text='EAN-13, QR ou tout autre code de scan physique.', max_length=50, null=True, unique=True, verbose_name='Code-barres (EAN/QR)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='coefficient_conversion',
            field=models.DecimalField(decimal_places=4, default=1, help_text="Nombre d'unités de stock par unité d'achat. Ex : 24 si 1 carton = 24 pcs.", max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Coefficient de conversion (achat → stock)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='conditions_stockage',
            field=models.CharField(blank=True, help_text="Ex : Conserver au frais entre 2 °C et 8 °C, à l'abri de la lumière.", max_length=200, verbose_name='Conditions de stockage'),
        ),
        migrations.AlterField(
            model_name='article',
            name='duree_vie_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Si renseigné, la date de péremption est calculée automatiquement à la réception (date_réception + durée_vie_jours).', null=True, verbose_name='Durée de vie (jours)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='methode_valorisation',
            field=models.CharField(choices=[('S', 'Prix standard (S) — fixé manuellement, écarts comptabilisés'), ('V', 'Prix moyen mobile (V) — recalculé automatiquement à chaque réception')], default='V', help_text='S = prix fixe standard. V = coût moyen pondéré recalculé à chaque réception.', max_length=1, verbose_name='Méthode de valorisation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix_standard',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Méthode S : prix fixé manuellement. Méthode V : mis à jour automatiquement (CMUP) à chaque entrée en stock.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix standard / CMUP (FCFA)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reference_externe',
            field=models.CharField(blank=True, help_text='Référence fabricant ou code article fournisseur principal.', max_length=100, verbose_name='Réf. externe / constructeur'),
        ),
        migrations.AlterField(
            model_name='article',
            name='unite_achat',
            field=models.ForeignKey(blank=True, help_text="Unité utilisée pour les commandes/réceptions (ex : carton). Si vide, identique à l'unité de stock.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles_en_achat', to='production.unitemesure', verbose_name="Unité d'achat"),
        ),
        migrations.AlterField(
            model_name='coutrevient',
            name='ecart_cout',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Coût total réel − (qté bonne × coût_standard). Positif = surcoût, négatif = économie.', max_digits=14, verbose_name='Écart coût global (FCFA)'),
        ),
        migrations.AlterField(
            model_name='coutrevient',
            name='ecart_rendement',
            field=models.DecimalField(decimal_places=2, default=0, help_text='(qté produite bonne − qté prévue) × coût_standard. Négatif = sous-production défavorable.', max_digits=14, verbose_name='Écart rendement (FCFA)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='code_barre',
            field=models.CharField(blank=True, db_index=True, help_text='EAN-13, QR ou tout autre code de scan physique.', max_length=50, null=True, verbose_name='Code-barres (EAN/QR)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='coefficient_conversion',
            field=models.DecimalField(decimal_places=4, default=1, help_text="Nombre d'unités de stock par unité d'achat. Ex : 24 si 1 carton = 24 pcs.", max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Coefficient de conversion (achat → stock)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='conditions_stockage',
            field=models.CharField(blank=True, help_text="Ex : Conserver au frais entre 2 °C et 8 °C, à l'abri de la lumière.", max_length=200, verbose_name='Conditions de stockage'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='duree_vie_jours',
            field=models.PositiveIntegerField(blank=True, help_text='Si renseigné, la date de péremption est calculée automatiquement à la réception (date_réception + durée_vie_jours).', null=True, verbose_name='Durée de vie (jours)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='methode_valorisation',
            field=models.CharField(choices=[('S', 'Prix standard (S) — fixé manuellement, écarts comptabilisés'), ('V', 'Prix moyen mobile (V) — recalculé automatiquement à chaque réception')], default='V', help_text='S = prix fixe standard. V = coût moyen pondéré recalculé à chaque réception.', max_length=1, verbose_name='Méthode de valorisation'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='prix_standard',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Méthode S : prix fixé manuellement. Méthode V : mis à jour automatiquement (CMUP) à chaque entrée en stock.', max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix standard / CMUP (FCFA)'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='reference_externe',
            field=models.CharField(blank=True, help_text='Référence fabricant ou code article fournisseur principal.', max_length=100, verbose_name='Réf. externe / constructeur'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='unite_achat',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Unité utilisée pour les commandes/réceptions (ex : carton). Si vide, identique à l'unité de stock.", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.unitemesure', verbose_name="Unité d'achat"),
        ),
        migrations.AlterUniqueTogether(
            name='reservationlot',
            unique_together={('ordre_fabrication', 'lot')},
        ),
    ]
