# Generated by Django 6.0.3 on 2026-03-23 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_typearticle_article_type_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalarticle',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="Type de l'article — gère les capacités métier (BOM, OF, achat).", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='production.typearticle', verbose_name='Type'),
        ),
    ]
